//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosExchange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public int ListingId { get; set; }
        public int ListerId { get; set; }
        public string VIN { get; set; }
        public int Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Trim { get; set; }
        public int KM { get; set; }
        public bool isNewCar { get; set; }
        public string CarType { get; set; }
        public string Color { get; set; }
        public string Drivetrain { get; set; }
        public string FuelType { get; set; }
        public string Transmission { get; set; }
        public Nullable<double> FuelEconomy { get; set; }
        public bool isAvailable { get; set; }
        public Nullable<double> SoldPrice { get; set; }
    
        public virtual Lister Lister { get; set; }
    }
}
